// Επικολλήστε τα δεδομένα σας από το CSV ανάμεσα στα backticks (`)
// Μορφή: ημερομηνία,ομαδα1,ομαδα2,διοργάνωση
const MATCHES_CSV = `24/09/26,PANATHINAIKOS AKTOR ATHENS,PARIS BASKETBALL,EL
30/09/26,PANATHINAIKOS AKTOR ATHENS,LDLC ASVEL VILLEURBANNE,EL
02/10/26,PANATHINAIKOS AKTOR ATHENS,MACCABI RAPYD TEL AVIV,EL
08/10/26,PANATHINAIKOS AKTOR ATHENS,FENERBAHCE ISTANBUL,EL
13/10/26,PARTIZAN MOZZART BET BELGRADE,PANATHINAIKOS AKTOR ATHENS,EL
16/10/26,PANATHINAIKOS AKTOR ATHENS,HAPOEL IBI TEL AVIV,EL
22/10/26,PANATHINAIKOS AKTOR ATHENS,KOSNER BASKONIA VITORIA-GASTEIZ,EL
27/10/26,PANATHINAIKOS AKTOR ATHENS,ARMANI OLIMPIA MILAN,EL
30/10/26,ANADOLU EFES ISTANBUL,PANATHINAIKOS AKTOR ATHENS,EL
04/11/26,REAL MADRID,PANATHINAIKOS AKTOR ATHENS,EL
13/11/26,PANATHINAIKOS AKTOR ATHENS,FC BARCELONA,EL
17/11/26,VIRTUS BOLOGNA,PANATHINAIKOS AKTOR ATHENS,EL
19/11/26,ZALGIRIS KAUNAS,PANATHINAIKOS AKTOR ATHENS,EL
24/11/26,VALENCIA BASKET,PANATHINAIKOS AKTOR ATHENS,EL
04/12/26,BESIKTAS ISTANBUL,PANATHINAIKOS AKTOR ATHENS,EL
11/12/26,PANATHINAIKOS AKTOR ATHENS,OLYMPIACOS PIRAEUS,EL
16/12/26,PANATHINAIKOS AKTOR ATHENS,CRVENA ZVEZDA MERIDIANBET BELGRADE,EL
18/12/26,FC BAYERN MUNICH,PANATHINAIKOS AKTOR ATHENS,EL
23/12/26,DUBAI BASKETBALL,PANATHINAIKOS AKTOR ATHENS,EL
29/12/26,FENERBAHCE ISTANBUL,PANATHINAIKOS AKTOR ATHENS,EL
07/01/27,MACCABI RAPYD TEL AVIV,PANATHINAIKOS AKTOR ATHENS,EL
12/01/27,PANATHINAIKOS AKTOR ATHENS,VALENCIA BASKET,EL
14/01/27,PANATHINAIKOS AKTOR ATHENS,FC BAYERN MUNICH,EL
21/01/27,HAPOEL IBI TEL AVIV,PANATHINAIKOS AKTOR ATHENS,EL
29/01/27,PANATHINAIKOS AKTOR ATHENS,ANADOLU EFES ISTANBUL,EL
02/02/27,PANATHINAIKOS AKTOR ATHENS,DUBAI BASKETBALL,EL
05/02/27,ARMANI OLIMPIA MILAN,PANATHINAIKOS AKTOR ATHENS,EL
12/02/27,OLYMPIACOS PIRAEUS,PANATHINAIKOS AKTOR ATHENS,EL
04/03/27,PANATHINAIKOS AKTOR ATHENS,BESIKTAS ISTANBUL,EL
09/03/27,KOSNER BASKONIA VITORIA-GASTEIZ,PANATHINAIKOS AKTOR ATHENS,EL
11/03/27,PARIS BASKETBALL,PANATHINAIKOS AKTOR ATHENS,EL
18/03/27,PANATHINAIKOS AKTOR ATHENS,ZALGIRIS KAUNAS,EL
23/03/27,LDLC ASVEL VILLEURBANNE,PANATHINAIKOS AKTOR ATHENS,EL
25/03/27,PANATHINAIKOS AKTOR ATHENS,PARTIZAN MOZZART BET BELGRADE,EL
02/04/27,FC BARCELONA,PANATHINAIKOS AKTOR ATHENS,EL
06/04/27,CRVENA ZVEZDA MERIDIANBET BELGRADE,PANATHINAIKOS AKTOR ATHENS,EL
08/04/27,PANATHINAIKOS AKTOR ATHENS,VIRTUS BOLOGNA,EL
15/04/27,PANATHINAIKOS AKTOR ATHENS,REAL MADRID,EL
26/9/26,,,Super Cup στη Ρόδο με συμμετοχή Ολυμπιακός, Παναθηναϊκός, ΑΕΚ, ΠΑΟΚ
27/9/26,,,Super Cup στη Ρόδο με συμμετοχή Ολυμπιακός, Παναθηναϊκός, ΑΕΚ, ΠΑΟΚ
11/9/26,,,2ο International Tournament Rhodes 2026 με συμμετοχή Παναθηναϊκού,Α.Ε.Κ.,Σπάρτακ Σουμπότιτσα
12/9/26,,,2ο International Tournament Rhodes 2026 με συμμετοχή Παναθηναϊκού,Α.Ε.Κ.,Σπάρτακ Σουμπότιτσα
13/9/26,,,2ο International Tournament Rhodes 2026 με συμμετοχή Παναθηναϊκού,Α.Ε.Κ.,Σπάρτακ Σουμπότιτσα
19/9/26,,,Τουρνουά «Παύλος Γιαννακόπουλος» με συμμετοχή Παναθηναϊκού,Παρτίζαν,ΠΑΟΚ,εκκρεμεί-πιθανόν Μπεσίκτας
20/9/26,,,Τουρνουά «Παύλος Γιαννακόπουλος» με συμμετοχή Παναθηναϊκού,Παρτίζαν,ΠΑΟΚ,εκκρεμεί-πιθανόν Μπεσίκτας
1/8/26,,,test2`;
